name: Waka Readme
on:
  push:
    branches:
      - '**'
  schedule:
    # Runs at 12am UTC
    # ... hopefully
    - cron: "0 0 * * *"
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: solonovamax/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_PROFILE_VIEWS: False
          SHOW_OS: False
          SHOW_LOC_CHART: False
          SHOW_LANGUAGE_PER_REPO: False
