name: Waka Readme
on: 
  push:
    branches:
      - main
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: solonovamax/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          HOW_LINES_OF_CODE: True
          LOCALE: en
          SHOW_OS: True
          SHOW_EDITORS: True
          SHOW_TIMEZONE: True
          SHOW_COMMIT: True
          SHOW_LANGUAGE: True
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_LOC_CHART: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_PROFILE_VIEWS: True
          SHOW_SHORT_INFO: True
